import { Router } from 'express';
import { authenticate, authorize } from '../../middleware/auth.middleware.js';
import { uploadDocument } from '../../middleware/document-upload.middleware.js';
import { validateBody, validateQuery } from '../../middleware/validate.js';
import { documentsController } from './documents.controller.js';
import { documentListQuerySchema, documentUploadSchema } from './documents.schemas.js';
export const documentsRouter = Router();
documentsRouter.post('/documents', authenticate, uploadDocument, validateBody(documentUploadSchema), documentsController.upload);
documentsRouter.get('/documents', authenticate, validateQuery(documentListQuerySchema), documentsController.listMine);
documentsRouter.get('/admin/documents', authenticate, authorize('admin'), validateQuery(documentListQuerySchema), documentsController.listAdmin);
