import { z } from 'zod';

import { TIME_MS, TIME_SECONDS } from '../shared/constants/time.js';

const PORT_MAX_LIMIT = 65_535;
const DEFAULT_PORT = 3000;
const JWT_SECRET_MIN_LENGTH = 32;
const DEFAULT_LOGIN_RATE_LIMIT_WINDOW_MS = TIME_MS.ONE_MINUTE;
const DEFAULT_LOGIN_RATE_LIMIT_MAX_ATTEMPTS = 5;
const DEFAULT_REGISTER_RATE_LIMIT_WINDOW_SECONDS = TIME_SECONDS.FIFTEEN_MINUTES;
const DEFAULT_REGISTER_RATE_LIMIT_MAX_ATTEMPTS = 3;
const DEFAULT_FORGOT_PASSWORD_RATE_LIMIT_WINDOW_SECONDS = TIME_SECONDS.FIFTEEN_MINUTES;
const DEFAULT_FORGOT_PASSWORD_RATE_LIMIT_MAX_ATTEMPTS = 3;
const DEFAULT_RESET_PASSWORD_RATE_LIMIT_WINDOW_SECONDS = TIME_SECONDS.FIFTEEN_MINUTES;
const DEFAULT_RESET_PASSWORD_RATE_LIMIT_MAX_ATTEMPTS = 3;
const DEFAULT_RESET_PASSWORD_TOKEN_CHECK_RATE_LIMIT_WINDOW_SECONDS = TIME_SECONDS.FIFTEEN_MINUTES;
const DEFAULT_RESET_PASSWORD_TOKEN_CHECK_RATE_LIMIT_MAX_ATTEMPTS = 10;
const DEFAULT_RESEND_VERIFICATION_EMAIL_RATE_LIMIT_WINDOW_SECONDS = TIME_SECONDS.ONE_DAY;
const DEFAULT_RESEND_VERIFICATION_EMAIL_RATE_LIMIT_MAX_ATTEMPTS = 3;
const DEFAULT_VERIFICATION_ATTEMPT_RATE_LIMIT_WINDOW_SECONDS = TIME_SECONDS.TEN_MINUTES;
const DEFAULT_VERIFICATION_ATTEMPT_RATE_LIMIT_MAX_ATTEMPTS = 5;

const envSchema = z.object({
  PORT: z.coerce.number().int().min(1).max(PORT_MAX_LIMIT).default(DEFAULT_PORT),
  MONGODB_URI: z.string().min(1, 'MONGODB_URI is required'),
  JWT_ACCESS_SECRET: z.string().min(JWT_SECRET_MIN_LENGTH, `JWT_ACCESS_SECRET must be at least ${JWT_SECRET_MIN_LENGTH} characters`),
  JWT_REFRESH_SECRET: z.string().min(JWT_SECRET_MIN_LENGTH, `JWT_REFRESH_SECRET must be at least ${JWT_SECRET_MIN_LENGTH} characters`),
  JWT_ACCESS_EXPIRES_IN: z.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN: z.string().default('7d'),
  OPENAPI_SERVER_URL: z.string().url().optional(),
  CORS_ORIGIN: z.string().optional(),
  REDIS_URL: z.string().url().optional(),
  APP_BASE_URL: z.string().url().default('http://localhost:5173'),
  WEB_URL: z.string().url().optional(),
  BREVO_API_KEY: z.string().optional(),
  BREVO_SENDER_EMAIL: z.string().email().default('no-reply@example.com'),
  BREVO_SENDER_NAME: z.string().default('ITTalent'),
  CLOUDINARY_CLOUD_NAME: z.string().min(1).optional(),
  CLOUDINARY_API_KEY: z.string().min(1).optional(),
  CLOUDINARY_API_SECRET: z.string().min(1).optional(),
  EMAIL_VERIFICATION_WINDOW_MS: z.coerce.number().int().positive().default(TIME_MS.ONE_DAY),
  RESET_PASSWORD_TOKEN_WINDOW_SECONDS: z.coerce.number().int().positive().default(TIME_SECONDS.ONE_HOUR),
  RESET_TOKEN_HISTORY_GRACE_SECONDS: z.coerce.number().int().positive().default(TIME_SECONDS.ONE_HOUR),
  AUTH_VERIFICATION_JOB_INTERVAL_MS: z.coerce.number().int().positive().default(TIME_MS.ONE_HOUR),
  LOGIN_RATE_LIMIT_WINDOW_MS: z.coerce.number().int().positive().default(DEFAULT_LOGIN_RATE_LIMIT_WINDOW_MS),
  LOGIN_RATE_LIMIT_MAX_ATTEMPTS: z.coerce.number().int().positive().default(DEFAULT_LOGIN_RATE_LIMIT_MAX_ATTEMPTS),
  REGISTER_RATE_LIMIT_WINDOW_SECONDS: z.coerce.number().int().positive().default(DEFAULT_REGISTER_RATE_LIMIT_WINDOW_SECONDS),
  REGISTER_RATE_LIMIT_MAX_ATTEMPTS: z.coerce.number().int().positive().default(DEFAULT_REGISTER_RATE_LIMIT_MAX_ATTEMPTS),
  FORGOT_PASSWORD_RATE_LIMIT_WINDOW_SECONDS: z.coerce.number().int().positive().default(DEFAULT_FORGOT_PASSWORD_RATE_LIMIT_WINDOW_SECONDS),
  FORGOT_PASSWORD_RATE_LIMIT_MAX_ATTEMPTS: z.coerce.number().int().positive().default(DEFAULT_FORGOT_PASSWORD_RATE_LIMIT_MAX_ATTEMPTS),
  RESET_PASSWORD_RATE_LIMIT_WINDOW_SECONDS: z.coerce.number().int().positive().default(DEFAULT_RESET_PASSWORD_RATE_LIMIT_WINDOW_SECONDS),
  RESET_PASSWORD_RATE_LIMIT_MAX_ATTEMPTS: z.coerce.number().int().positive().default(DEFAULT_RESET_PASSWORD_RATE_LIMIT_MAX_ATTEMPTS),
  RESET_PASSWORD_TOKEN_CHECK_RATE_LIMIT_WINDOW_SECONDS: z.coerce.number().int().positive().default(DEFAULT_RESET_PASSWORD_TOKEN_CHECK_RATE_LIMIT_WINDOW_SECONDS),
  RESET_PASSWORD_TOKEN_CHECK_RATE_LIMIT_MAX_ATTEMPTS: z.coerce.number().int().positive().default(DEFAULT_RESET_PASSWORD_TOKEN_CHECK_RATE_LIMIT_MAX_ATTEMPTS),
  RESEND_VERIFICATION_EMAIL_RATE_LIMIT_WINDOW_SECONDS: z.coerce.number().int().positive().default(DEFAULT_RESEND_VERIFICATION_EMAIL_RATE_LIMIT_WINDOW_SECONDS),
  RESEND_VERIFICATION_EMAIL_RATE_LIMIT_MAX_ATTEMPTS: z.coerce.number().int().positive().default(DEFAULT_RESEND_VERIFICATION_EMAIL_RATE_LIMIT_MAX_ATTEMPTS),
  VERIFICATION_ATTEMPT_RATE_LIMIT_WINDOW_SECONDS: z.coerce.number().int().positive().default(DEFAULT_VERIFICATION_ATTEMPT_RATE_LIMIT_WINDOW_SECONDS),
  VERIFICATION_ATTEMPT_RATE_LIMIT_MAX_ATTEMPTS: z.coerce.number().int().positive().default(DEFAULT_VERIFICATION_ATTEMPT_RATE_LIMIT_MAX_ATTEMPTS),
});

export const env = envSchema.parse(process.env);

export type Env = typeof env;
